### ISSUE TITLE
failed to wait? 

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1300] opened 2017-05-06 22:42 UTC
The message "Failed to wait '2500' ms." means what? 
http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=45946701

Thanks!

**Comment by vertigo17** [comment] 2017-05-07 21:32
That happen when the Exception InterruptedException is reached.
That Execption is thrown when a thread is waiting, sleeping, or otherwise occupied, and the thread is interrupted, either before or during the activity.

Not sure in that specific case why.
I added the exception detail message to better see why.

I hope that test have the same issue in QA and in that case, we will be able to check it.

**Comment by ruirpr** [comment] 2017-05-24 14:39
Hi, 
we have now this result
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=46724486

Failed to wait '1750' ms due to Exception : java.lang.InterruptedException: sleep interrupted

**Comment by cassarreb** [comment] 2018-02-08 09:25
Hi,
This error sometimes arises when executing tests in parallel. Has any progress been made about it please?

Thanks.

**Comment by akatmiranda** [comment] 2018-04-16 10:51
Hi!

I see this thread had no updates for the recent past.
This is happening very often in our tests. 
Message: "Failed to wait '8000' ms due to Exception : java.lang.InterruptedException: sleep interrupted".

Some examples:
http://192.168.135.32/Cerberus/TestCaseExecution.jsp?executionId=57943319
http://192.168.135.32/Cerberus/TestCaseExecution.jsp?executionId=57943430

Do you have some solution or ideas on this?
Thanks in advance for your feedback on this.

**Comment by akatmiranda** [comment] 2018-05-30 12:12
Hi! Any news about this?

This has been happening a lot lately in our test and is gaining some importance has it is the cause of some of our failed executions, specially in our iPhone tests.

http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=59824614
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=59827101

![image](https://user-images.githubusercontent.com/38046035/40719224-d3ce4312-640a-11e8-99d0-5569d7943e5d.png)


Can you please address this?
TY

**Comment by vertigo17** [comment] 2018-05-30 12:16
I checked a couple of forum and looks like what is proposed is to ignore the Exception.
I will try to comit something soon that do not considere that exception as an error and we will see if on those case the sleep is done or not.

**Comment by vertigo17** [comment] 2018-07-19 19:59
@akatmiranda, @cassarreb,  @ruirpr Can you confirm if this is fixed ?

**Comment by vertigo17** [comment] 2018-07-29 15:08
I close it as no feedback.

**Closed by vertigo17** 2018-07-29 15:08 UTC
Labels: Nat : bug, Perim : ENGINEAction, Prio : 2 normal
