### ISSUE TITLE
Dockerized cerberus extension?

### ISSUE THREAD

**Issue by jdimanche** [cerberustesting/cerberus-source#1787] opened 2018-07-12 12:08 UTC
Hi,

You gave the dockers to run Cerberus, do you have any updated docker with this sikuli extension pre-installed before I start to do it.

Thank's
Jérôme.

**Comment by vertigo17** [comment] 2018-07-14 21:33
no, There are currently no docker for sikuli extension.
Feel free to propose a version.
Make sure you propose it to https://github.com/cerberustesting/cerberus-extension-sikuli

**Comment by vertigo17** [comment] 2019-04-26 19:34
Duplicate of https://github.com/cerberustesting/cerberus-extension-sikuli/issues/4

**Closed by vertigo17** 2019-04-26 19:34 UTC
Labels: Nat : enhancement, Perim : OTHERS, Prio : 2 normal
