### ISSUE TITLE
Open URL not available for apk

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#2009] opened 2019-08-19 13:36 UTC
Hello,

Some time ago we were able to launch tests to an android browser and now the action OpenURL is not available for APK type. We have some requests to create tests for deeplinks on android devices can you make it available again?

http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=80560761

Best Regards,
Cerberus Version : 4.2-SNAPSHOT-1421

**Comment by vertigo17** [comment] 2020-07-09 11:42
Can you confirm that the issue is a duplicate of #2092 and as a consequence now fixed ?
Thanks.

**Closed** 2020-07-10 20:42 UTC
Labels: Nat : bug, Perim : ENGINEActionApps, Prio : 1 high+, Status : waiting feedback
