### ISSUE TITLE
[bug] firefox version > 47 + Gecko driver + browserstack 

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1539] opened 2017-11-07 16:12 UTC
Hello,

There is a unexpected issue in one of the Cerberus campaign. We have one action set to 'click' on a element selected using xpath : 

![image](https://user-images.githubusercontent.com/30227758/32503749-4dba4252-c3de-11e7-9316-19dabd8adebe.png)

But running this campaign, this action seems to be executed as a 'wait' : 

![image](https://user-images.githubusercontent.com/30227758/32503798-73adbd68-c3de-11e7-8d4f-41f81b882a35.png)

The xpath selection doesn't seem to cause any problem but the click is not done which make the following steps fail.

Any ideas ?
Thanks

**Comment by MowglieRed** [comment] 2017-11-22 12:10
it seems that it concerns only browser stack. 
at least optimize the error message

**Comment by Nouxx** [comment] 2017-12-05 09:50
Update : 

- Workaround  : add 'wait' action (2 seconds maximum) to allow element to be properly charged

- Suggestion : for every click action, force (depending on the application / campaign) a _verifiyElementClickable_ control on the triggered element. This could could improve the reliability of the testcases and stay user friendly. However, the impact of such change has to be investigated

**Comment by ryltar** [comment] 2017-12-12 13:21
it concerns only browser stack firefox version <= 47.
if browserStack Firefox version > 47 , we have this error and double click which not work due to mouseMoveTo error

**Comment by ryltar** [comment] 2017-12-12 15:56
firefox version > 47 need marionette (gecko driver). By default, selenium is in 2.x version and don't need a gecko driver in browserStack

**Comment by ryltar** [comment] 2017-12-13 15:16
it seems that the problem occured with browserstack firefox version between 48 and 58. Waiting firefox 59 version to test.

**Comment by vertigo17** [comment] 2017-12-13 15:56
@ryltar , we still need to better handle the error message to make it clear that it failed to find the element.
Considering that the issue is intermittent from selenium, I also think we need to find a way to make it more robust at Cerberus level by an automatic retry. We can try to loop 3 time until object is not null. When issue is fixed on Selenium/Gecko side that will no longuer be used but for 48 to 58 version, that will improve the result.

**Comment by ryltar** [comment] 2017-12-13 16:30
The problem of click which is transformed into a wait is solved by using an Action object like selenium docs say. I don't have yet push on github 

On browserStack firefox only, keypress, double click and click are not working due to firefox version. Selenium say that MouseMouveTo operation is not supported but it seems that in firefox 59, this problem is solved. Retrying click with a loop will not solved the problem because of MouseMouveTo

A little workaround trick is to set the version of firefox to 47

It's a very stange problem because on my localhost, i tried with the same gecko , selenium and firefox version and all action are supported

Maybe just a problem with browserstack firefox.

**Closed** 2018-03-12 15:46 UTC
Labels: Nat : bug, Perim : ENGINEActionWeb, Prio : 2 normal
