### ISSUE TITLE
Add Application option in Data Library configurations

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#897] opened 2016-08-25 10:15 UTC
Would it be possible to also defined the application for which the Data Library is intended to?
This option was available for the Test Data and can be very handy when tests are running for more than one application (for example web tests that are executed for the main site and for Mobile)

Test Data options:
![image](https://cloud.githubusercontent.com/assets/17747042/17965403/7023504c-6ab4-11e6-8ae1-569481146b2b.png)

Data Lib options:
![image](https://cloud.githubusercontent.com/assets/17747042/17965433/95d69ccc-6ab4-11e6-86c9-adc91a39a877.png)

**Comment by vertigo17** [comment] 2016-08-25 12:19
In fact using properties to store url seems risky.
Url are just like button names or menus or any gui objects. For me we should not use testdatalib neither testdata for that but more use step feature to encaps actions and reuse them from 1 testcase to another.
Testdata should be used to gather from database data that are necessary for testing such as specific customer number or product ids and those should be the same on 2 different applications (but could be different from 2 systems because each system has its own databsse not necessary synchro with other systems even if the data is the same).
How easy is it to move to use step feature? If ok, i suggest to close the issue if not enought, we could introduce a library of object (i think an issue already exist on that).

**Comment by vertigo17** [comment] 2016-08-25 13:01
Duplicate of #856

**Comment by vertigo17** [comment] 2016-11-22 01:06
I close the issue as #856 has been implemented and closed.
Use Application Object with the same name on the 2 application.
Put the specific URL per application inside value.

**Closed by vertigo17** 2016-11-22 01:06 UTC
Labels: Perim : ENGINEAction
