### ISSUE TITLE
TC Page / Bug on Use step creation after modif order number in libraries TC

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#869] opened 2016-07-19 07:52 UTC
Cerberus Version : 1.1.5-SNAPSHOT

After I create a new library, say in position 5 out of 10 libraries.
When I "use step" that library, order is not renewed when creation of new step into Test Case.

To say differently, order number of use-step list is renewed when steps already existed. If click "add-step" then "use-step", order is still on "technical step number"

thx for the nice work !
regards,
PF

**Comment by abourdon** [comment] 2016-07-19 14:25
Hi @pfoucray,

Could you please be more specific about your issue? Because I'm trying to reproduce from my side but without success.

Cheers,
Aurélien

**Comment by bcivel** [comment] 2017-01-02 22:23
Hi @pfoucray ,
We won't fix that issue as this page is now deprecated. 
Thanks for your contribution
Benoit

**Closed by bcivel** 2017-01-02 22:23 UTC
Labels: Perim : GUITest
