### ISSUE TITLE
Issues with the queue

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1449] opened 2017-08-18 12:16 UTC
Hello,

I still meet problems with the queue system, for example the two following screenshots are taken at the same time, but as you can see they are not consistent.
In the first one 4 test cases are executing (which is expecting with pool size parameter) but in the second one, we only see 2 PE status. Could you have a look please ?
You can reproduice by running Cerberus campaign in demo environment.

![image](https://user-images.githubusercontent.com/18569182/29458222-5387d2e4-841e-11e7-9df1-65e70d3e8aa0.png)
![image](https://user-images.githubusercontent.com/18569182/29458248-67b811a2-841e-11e7-8c5b-f2f32468c3c2.png)
Thank you !

Cerberus Version : 1.1.14-SNAPSHOT-1202

**Comment by Galand-V** [comment] 2017-08-18 13:43
Also, if the TestCase is longer than 5 minutes,  it automaticaly creates a new execution ID even if the other instance is not finished. 

![sans titre-1](https://user-images.githubusercontent.com/29098010/29461256-55f838a4-842b-11e7-9cce-af86fea95355.jpg)

The "PE execution" are not present in the queue.

**Comment by vertigo17** [comment] 2017-08-18 21:55
The 5 minute retry is a known issue. We need to remove the automatic retry of runtestcase servlet. Until this is changed/fixed, please change the timeout parameter of queue system to a very long period to avoid the issue 30 min for ex.

Regarding the other issue, i need more detail. What was the status of the 4 running test case in the report by tag screen ? I guess 2 of them are PE and the 2 others could be QU again in case there were a retry or already have the final status. 
Status can change quite quickly and nothing can garantee that view are consistent each other. At the end of those 4 executions, was the report screen correct ?
Let's check that together next week.

**Comment by vertigo17** [comment] 2017-08-19 13:53
@Galand-V parameter to set is: 
cerberus_queueexecution_timeout
you can put 1800000 in order to set it at 30 minutes.

@R-Loic Regarding the other issue, it is more related to reporting than queuing system.
I checked the campaign execution and all executions were submitted correctly.
What I believe confuse you is that the reportingByTag page groups the execution per:
1/ TestCase 2/ Environment 3/ Country but alos 4/ browser.
The problem here is that all executions are requested for firefox browser and, if for GUI application it make sense, for SRV application it makes no sense.
The queue is having the firefox parameter but as soon as the execution starts, browser is forced at empty.
For that TestCase, Environment and country, the entry in the queue appears on reporting as firefox and entry in execution appears in empty.
In order to prevent that to happened, I corrected the AddToExecutionQueue servlet in order to change the browser for non GUI application. I will probably have to do it also in servlet used by RunTestCase page.
https://github.com/cerberustesting/cerberus-source/commit/998ef68c5f990aa24a30fcf5d47ea95c7292220f

A second issue was already correctly that could also explain the issue:
https://github.com/cerberustesting/cerberus-source/commit/42f88f38fd528e8fa0ee26b2c061be24535f72cf
The executing queue entry were still displayed in ReportingByTag page. This is also the reason why your snapshot reports 67 executions when in fact it should have been 65. Probably 2 executions were still appearing in queue on reporting screen when it should have disappeared.

I beleive the version deployed does not have any of those 2 fixes done 10th of August. Let's upgrade and try to reproduce.

**Comment by vertigo17** [comment] 2017-08-19 20:15
@Galand-V parameter to set is: 
cerberus_queueexecution_timeout
you can put 1800000 in order to set it at 30 minutes.

@R-Loic Regarding the other issue, it is more related to reporting than queuing system.
I checked the campaign execution and all executions were submitted correctly.
What I believe confuse you is that the reportingByTag page groups the execution per:
1/ TestCase 2/ Environment 3/ Country but alos 4/ browser.
The problem here is that all executions are requested for firefox browser and, if for GUI application it make sense, for SRV application it makes no sense.
The queue is having the firefox parameter but as soon as the execution starts, browser is forced at empty.
For that TestCase, Environment and country, the entry in the queue appears on reporting as firefox and entry in execution appears in empty.
In order to prevent that to happened, I corrected the AddToExecutionQueue servlet in order to change the browser for non GUI application. I will probably have to do it also in servlet used by RunTestCase page.
https://github.com/cerberustesting/cerberus-source/commit/998ef68c5f990aa24a30fcf5d47ea95c7292220f

A second issue was already correctly that could also explain the issue:
https://github.com/cerberustesting/cerberus-source/commit/42f88f38fd528e8fa0ee26b2c061be24535f72cf
The executing queue entry were still displayed in ReportingByTag page. This is also the reason why your snapshot reports 67 executions when in fact it should have been 65. Probably 2 executions were still appearing in queue on reporting screen when it should have disappeared.

I beleive the version deployed does not have any of those 2 fixes done 10th of August. Let's upgrade and try to reproduce.

**Comment by Galand-V** [comment] 2017-08-21 09:59
Hello @vertigo17, 

Thank you for the complete answer ! 

I tried your solution. It is still not working with the new "cerberus_queueexecution_timeout" parameter.

**Comment by bcivel** [comment] 2017-08-21 20:21
Hello @Galand-V 
I disabled the auto retry made when timeout was reached.
So it should be fixed now

**Closed** 2017-09-01 21:33 UTC
Labels: Nat : bug, Perim : Queueing system, Prio : normal
