### ISSUE TITLE
incorrect step condition when used steps

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2237] opened 2021-02-11 12:36 UTC
Hello,

As you can see with this used step
![image](https://user-images.githubusercontent.com/30227758/107636953-b6db6a00-6c6d-11eb-9e0e-ae91fbccf20e.png)

The corresponding library step has the correct condition definition
![image](https://user-images.githubusercontent.com/30227758/107637151-f609bb00-6c6d-11eb-8b69-e0f808ff4c13.png)

**Comment by vertigo17** [comment] 2021-02-11 20:11
Hello @Nouxx, This is a duplicate of #2182 and was already corrected.
It will be available in next release.

**Closed by vertigo17** 2021-02-11 20:11 UTC
