### ISSUE TITLE
Tests outside the The Build/Revision are still displayed on Report

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1707] opened 2018-04-25 20:09 UTC
Cerberus Version : 3.2-1296

Hello,

Actually, when I execute a campaign which contains some test outside the build or the revision active, they are still displayed on the report with the QUEUE status with the comment "The Build/Revision of test case isn't in the range of build."

<img width="554" alt="capture d ecran 2018-04-25 a 22 09 48" src="https://user-images.githubusercontent.com/33724879/39270148-7450ae70-48d5-11e8-919f-9deaa53a0fe9.png">

<img width="1251" alt="capture d ecran 2018-04-25 a 22 04 35" src="https://user-images.githubusercontent.com/33724879/39270056-1f22cc6c-48d5-11e8-8177-47113d967e06.png">

Is it possible to remove them completely from the report ? or display them with an other status than QU ?

**Comment by vertigo17** [comment] 2018-04-28 12:34
We will split QU status that are still waiting for beeing executed from QU status that are finished (DONE, CANCELLED or in ERROR).
I propose 
QU --> QUEUED
QE --> All other status.

**Comment by vertigo17** [comment] 2018-04-28 13:51
Still missing a nicer looking on the color.

**Comment by vertigo17** [comment] 2018-05-02 14:51
Duplicate of #1607

**Closed by vertigo17** 2018-05-02 14:51 UTC
Labels: Nat : enhancement, Perim : ENGINETransversal, Prio : 2 normal
