### ISSUE TITLE
Error when not able to add testcase to queue

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2018] opened 2019-09-23 09:16 UTC
Hello,

I currently can't launch a campaign from the Run page.

The "processing" loader is blocked and looking at the network console 
![image](https://user-images.githubusercontent.com/30227758/65414179-74ed2200-ddf3-11e9-848e-4997bf9208ac.png)

Can we make sure the front returns a more user friendly error?

**Comment by vertigo17** [comment] 2019-09-23 19:36
I suppose this is a duplicate of #1835

**Comment by vertigo17** [comment] 2019-09-23 19:40
if error because require an authentification please close it and confirm duplicated.
if a 500 error please provide a trace of the call.

**Comment by vertigo17** [comment] 2019-09-29 19:13
Following our discution, the issue is not a duplicate of #1835.
Please provide a way to reproduce the 500 error.
Campaign name + browser.

**Comment by Nouxx** [comment] 2019-10-07 11:42
Env : https://qa.cerberus-testing.org
Campaign : Cerberus_campaign (every fields are pre filled)
Browser : Chrome (latest)

**Comment by vertigo17** [comment] 2019-10-23 20:09
I guess this is fixed following commit https://github.com/cerberustesting/cerberus-source/commit/7e935cd24d282987f8f0d0241c775130a0be93dd
Please reopen if not the case.

**Closed by vertigo17** 2019-10-23 20:09 UTC
Labels: Nat : bug, Perim : GUIExecution, Prio : 1 high+
