### ISSUE TITLE
RadioButton click / Timeout / lost connection to Selenium Server

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#758] opened 2016-05-13 08:14 UTC
Cerberus Version : 1.1.4-SNAPSHOT

It seems that I can't click some radio buttons.
Don't realy understand why, cause some tests (which aren't mine) work on that, while mine don't.
Thing is I copy/pasted an action working somewhere, never working for me.

Here is what cerberus returns : 2016-05-12

CA  11:29:20.7  640 ms  1   Select So Colissimo delevery method     click data-cerberus=radioButton_delivery_deliveryMethodChoice_soColissimo1

> >  The test case is canceled due to lost connection to Selenium Server!

Regards,
PF

**Comment by bcivel** [comment] 2016-09-13 21:22
Dear @pfoucray,

Could you provide more details for me to understand the issue?

What I suspect is maybe a default in testcase implementation. But anyway, it could be interresting to have concrete way to reproduce the issue "lost connection to Selenium Server".

If you can reproduce it, could you provide concrete example? If you can't, could you close the issue?

Thanks for your contribution
Benoit

**Comment by bcivel** [comment] 2016-12-10 15:08
Can't reproduce. It may be a problem in the impementation itself

**Closed by bcivel** 2016-12-10 15:08 UTC
Labels: Perim : ENGINEActionWeb
