### ISSUE TITLE
The TestCaseExecution page is loading all executions by default

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#1145] opened 2017-01-23 12:49 UTC
By default, the TestCaseExecution page is loading all executions by default because no filter is applied on the number of retrieved elements. Unfortunately, the page is not usable until all executions are loaded.

IMHO, we have to define at most 10 visible executions by default. Then user could apply a different filter according to its need.

I tag this issue as bug because filter has always to be set and it is quite urgent.

**Comment by bcivel** [comment] 2017-01-24 20:34
Hi @abourdon ,
I can not reproduce the issue. 
But it could be because some stuff have been done on this page since the release (mainly the change of template generating the table).
Could you confirm you still reproduce
Thanks
Benoit

**Comment by bcivel** [comment] 2017-01-25 22:05
Hi @abourdon , @R-Loic 
Fixed with that commit c64b7d7

It was a mistake from my side trying to get the table calling .dataTable() instead of DataTable().

First function instanciate the table even if table already generated, second one only retrieve the table.

Instanciating the table again produced 3 calls to the servlet, that generated all the strange behaviors we had on this page, depending on the velocity on the answers.

**Closed by bcivel** 2017-01-25 22:05 UTC
Labels: Awaiting Feedback, bug, Perim : GUIExecution
