### ISSUE TITLE
[Evolution] Cross test with Selenium & Appium

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1883] opened 2018-10-26 11:29 UTC
Hello,

I want to use either Selenium robot and Appium robot on the same test case.
Is it possible to add this feature ?

**Comment by nicodeur** [comment] 2018-10-30 10:56
Hello,

We already thinked to add possiblity to execute distinct `testcase` with `Selenium / Appium / Sikuli` on the same `campaign` for exemple.

But execute `Selenium` and `Appium` on the same `testcase` is an other history ... How to know if the action must be executed by `Selenium` or `Appium` on the testcase ? 

Several possiblities can be implemented with new action : 
  * `switchRobot` :  give possibility to easily switch on technology of the Robot (Selenium / Appium / Sikuli). 
  * `executeTestCase` : give possibility to call a testCase, and waiting the result of it.

In all case , we have to add an information on the robot so that Cerberus can know wich robot use on a `testcase` (ex : add attribute `technologie (Selenium / Appium / Sikuli)` on robot)

What do you think about it @bcivel @vertigo17  ??

**Comment by vertigo17** [comment] 2018-11-01 19:11
The best is to share together on that but for me the target is to implement the item in the roadmap called 'Queue Dependency improvements'.
As a consequence, for me this issue is a duplicate of #1827.

**Comment by nicodeur** [comment] 2018-11-02 12:54
Hi @vertigo17,

Yes it would be did that we want. We can discuss about it on the next meeting!

**Comment by nicodeur** [comment] 2018-11-12 12:57
duplicate of #1827

**Closed by nicodeur** 2018-11-12 12:57 UTC
Labels: Nat : enhancement, Perim : ENGINEAction, Perim : Queueing system, Prio : 2 normal
