### ISSUE TITLE
Empty user agent on test case header

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#2169] opened 2020-09-04 15:42 UTC
Hi,

test cases that have a user agent set (on mobile/tablet tests for example) have the user agent empty on header despite that user agent is set on database.

Some example:
![image](https://user-images.githubusercontent.com/14328346/92256241-66482f80-eecb-11ea-852b-029d452030f4.png)

On data base:
![image](https://user-images.githubusercontent.com/14328346/92256296-72cc8800-eecb-11ea-94a6-4842608aadca.png)

This is happening for all test cases that have user agent set.

Even if we try to set it on header and save it, on header it stays empty.

Also, when we try to write something on user agent field we have a list of suggestions that are user names.

![image](https://user-images.githubusercontent.com/14328346/92256847-26ce1300-eecc-11ea-8a68-e7b339c1f0d5.png)

Can this be checked please?

Thanks

**Comment by vertigo17** [comment] 2020-09-10 18:33
The autocomplete issue was fixed but I was not able to reproduce the saving issue.
Maybe fixed by a previous commit.
Please check and reopen if necessary.

**Closed** 2020-09-10 18:32 UTC
Labels: Nat : bug, Perim : GUITest, Prio : 0 high++, TestCase : ToBeCreated
