### ISSUE TITLE
Upload file from windows explorer

### ISSUE THREAD

**Issue by htopoff** [cerberustesting/cerberus-source#1714] opened 2018-04-30 07:02 UTC
Hi,

I encounter same issue as #862 
I want to select a file from the windows explorer pop-up.
Keypress ENTER didn't work at all.

How can I do that ?

**Comment by vertigo17** [comment] 2018-05-02 15:20
Duplicate of #1303. 
Basicly those interactions are not web based but browser specific. As a cpnsequence those interaction are out of selenium scope. 
3 possible solutions :
- Either use linux with keypress enter. Seems it still work. 
- either force the filepath directly on the web form. 
- either use sikuli but that will become os dependant.

**Closed by vertigo17** 2018-05-02 15:20 UTC
