### ISSUE TITLE
Properties not defined return KO

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1263] opened 2017-04-07 09:22 UTC
Hi,

tests with properties not defined for some countries returns KO, instead of a "warning".

Example: 
![image](https://cloud.githubusercontent.com/assets/14328346/24793957/cc25f9a8-1b7b-11e7-9e23-e035909a8699.png)

![image](https://cloud.githubusercontent.com/assets/14328346/24793968/da0804a8-1b7b-11e7-8a30-0866dba2758d.png)

On PROD:
![image](https://cloud.githubusercontent.com/assets/14328346/24793975/e1b4c06a-1b7b-11e7-9b57-6a3e9cbe6690.png)

Is this a new behavior?

Cerberus1.1.12-SNAPSHOT-1126 in qa

Can you please check and advise?

Thanks

**Comment by vertigo17** [comment] 2017-04-07 12:32
This is a new behaviour on any decode , 
if you use syntax %LOGIN_LAYER% and property does not exist, the control/action will execute anyway with the %LOGIN_LAYER% value.
If you want to be strict and Fail the test incase the property do not exeict, please prefer the syntax:
%property.LOGIN_LAYER%.

Any decoded text that still have %property. or %system. or %object. after the decode operation should fail.

This way you can tune if you want to fail of not.

**Comment by j0hnsa** [comment] 2017-04-07 13:23
Hello,

Since this is the expected behavior the issue can be closed.

Thanks and Regards

**Comment by RobertoAbraul** [comment] 2017-04-07 13:38
Hi @vertigo17 ,

we tried to use the property like you described but after the test ended it stays FA.

http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=44448941

Shouldn't the test be ok with only that control FA?
![image](https://cloud.githubusercontent.com/assets/14328346/24802349/8e0e106e-1b9f-11e7-85bd-42275ba3d405.png)

It's ok if property exists:
![image](https://cloud.githubusercontent.com/assets/14328346/24802363/a602aac2-1b9f-11e7-903b-64b8910d3fdc.png)


Can you please advise?

Thanks.

**Comment by vertigo17** [comment] 2017-04-10 20:53
No, a FA controls means that the control failed to executed. That cannot be interpreted as OK.
FA mean that the control needs to be corrected.
In your case, you can add a condition on the property exist so that the control will not be executed (it will be reported as NA).

Any Step, Action or Control that Fail, should report the full execution to be Failed so that correction on the testcase are performed.

**Comment by vertigo17** [comment] 2017-04-11 21:29
I close the issue as this is the expected behaviour.
That will be an opportunity to clean or put condition on control that was not done on some tests.
Please reopen if further question on the topic.

**Closed by vertigo17** 2017-04-11 21:29 UTC
Labels: Nat : bug, Perim : ENGINEProperty, Prio : major
