### ISSUE TITLE
Retries doesnt work ?

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1052] opened 2016-12-12 09:32 UTC
Hi,

Retries doesnt work ?
When we set retries to 1, it dosnt load app url on execution.

We need to handle 'false KO' than happen sometimes while monitoring 

Thanks

**Comment by vertigo17** [comment] 2016-12-12 22:30
We cannot reproduce it.
In order to better understand can you report the configuration of the testcase and the corresponding execution result. 
What is the property config where the retry do not work ?
What is the associated message ?

**Comment by vitoo** [comment] 2016-12-13 09:40
Execution setting : 
![image](https://cloud.githubusercontent.com/assets/995694/21134950/47607f82-c120-11e6-934b-c138199ea7c0.png)

It oppen 2 browser and dont load any url : 
![image](https://cloud.githubusercontent.com/assets/995694/21134976/5a6603ae-c120-11e6-9f7e-eae7f39981a1.png)

Failed to open 'https://intmonnorauto.norautointernational.com/'. null
![image](https://cloud.githubusercontent.com/assets/995694/21134991/67829aac-c120-11e6-926b-fec4f10f667a.png)

___

With Retries : 0, test case is executed, page is loaded ...

Do it work for you if you set Retries 1 or more ?

**Comment by vitoo** [comment] 2017-01-09 14:45
I think It should help our monitoring to fix this

Sometimes 5% of test cases fail for no reason

**Comment by vitoo** [comment] 2017-02-03 08:37
Can you take a look to this ?

Thanks a lot 😀

**Comment by vitoo** [comment] 2017-03-03 10:21
The need for us is on our Angular application where selenium had some random fails ( false KO ).
When we relaunch the fails, it works well.

**Comment by bcivel** [comment] 2017-03-03 22:17
Fixed with my last commit.
Notice that if you set retries > 0 with synchroneous = N, the testcase will be executed once and a warn log will be raised.

**Closed by bcivel** 2017-03-03 22:17 UTC
Labels: Perim : ENGINETransversal

**Comment by vitoo** [comment] 2017-03-06 15:25
Thanks !

Will you plan a new stable release soon ?

**Comment by vitoo** [comment] 2017-03-28 08:45
Hi @bcivel ,

Not an issue : the retrie only work on multiple execution

Issue : it works on my local windows, not on linux remote selenium node, does it work for you with this version ?

**Comment by vitoo** [comment] 2017-03-28 09:22
I've put my log above

if it can help

**Comment by bcivel** [comment] 2017-03-28 09:45
Hi @vitoo ,
Are you pointing to the node directly or to the hub?
Is the ip:port 10.130.114.205:4444 the one of the hub or the node?

**Comment by vitoo** [comment] 2017-03-28 09:49
It's the hub

**Comment by bcivel** [comment] 2017-03-28 12:12
on both execution? same IP, same port?

**Comment by vitoo** [comment] 2017-03-28 12:22
yes 
```
Selenium Server IP = 10.130.114.205
Selenium Server Port = 4444
```

**Comment by vitoo** [comment] 2017-04-04 14:10
works with DB reset of cerberus locally

**Comment by vitoo** [comment] 2017-04-04 15:54
Hi,

With a fresh install, still the same error on linux, retrie works on windows
