### ISSUE TITLE
keypress "SEARCH" not working for smartphone

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#861] opened 2016-07-12 19:58 UTC
Hello,

We've started to execute tests for smartphone and the keypress action is not working although it say it does, can you take a look?
TC tablet: http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=34238189
TC smartphone: http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=34248524

Thanks

**Comment by abourdon** [comment] 2016-07-18 13:41
Hi,

Is the Android version the same between your tablet and smartphone? Did you check if the "search" icon is displayed on the smartphone's keyboard?

Another thing: I can see you have an other test case  named "Check the behaviour of the search engine - SMARTPHONE" and the last execution was OK. Is the bug still occurs? 

Regards,
Aurélien

**Comment by j0hnsa** [comment] 2016-07-27 10:07
Hello Aurélien,

Sorry for the late reply.The search icon is present on both devices.
About the versions tablet uses Android 6.0.1 as well as the smartphone.

The last execution was a false OK as I was just testing the test implementation and manual action was executed.
Last TC executed on smartphone:

http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=34772500

Thanks

**Comment by j0hnsa** [comment] 2016-09-07 16:15
Hello,

Strange Behavior is happening with this issue. On the same device when running tests for version 6.1 (under android4 devices) keypress Search works but when running the latest version of the apk (7.4.4.2) keypress does not work, can you check what can be done?

Thanks
Best Regards

**Comment by abourdon** [comment] 2016-09-13 14:12
Hi,

Is the search icon is also present on 7.4.4.2 version?

Regards,
Aurélien

**Comment by j0hnsa** [comment] 2016-11-09 16:19
Hello Aurelien,

Yes indeed it is present. See screen captures from the app in attachment.

Thanks
Best Regards
![search_v7](https://cloud.githubusercontent.com/assets/16339891/20145509/453093f2-a698-11e6-80eb-5038cd16f2b5.png)
![search_v6](https://cloud.githubusercontent.com/assets/16339891/20145510/4532253c-a698-11e6-85e8-0f7229004ebc.png)

**Comment by j0hnsa** [comment] 2016-11-30 12:23
Hi Aurelien,

Can you prioritize this issue, would be important to improve the Android Tests.

Thanks,
Best Regards

**Comment by abourdon** [comment] 2016-12-16 15:26
Hi @j0hnsa,

Sorry for the late reply.

Keypress is application implementation dependent. Actually, if application does not listen to the pressed key, then nothing will appear. I cannot test the latest version because of an error during application starting...

By the way, I just fixed the behaviour when pressing to the SEARCH key.
Could you please try with the Cerberus SNAPSHOT version? 

For information, there are the allowed keypress code you can use with Cerberus:
- RETURN
- ENTER
- SEARCH
- BACKSPACE
- BACK 

Regards,
Aurélien

**Comment by j0hnsa** [comment] 2016-12-19 17:56
Hi Aurelien,

I Tried on http://192.168.134.197/CerberusQA but still with no success. the action is executed but no key is pressed... Any clue?
Thanks

**Comment by j0hnsa** [comment] 2016-12-19 17:57
Please note that I've tried with:
RETURN
ENTER
SEARCH

Thanks and Best Regards

**Comment by abourdon** [comment] 2017-04-04 14:34
I think we are correctly using the Appium's client to send keys as the SEARCH one. But there is a bug from Appium which could be the cause: https://github.com/appium/java-client/issues/265

A (not portable) workaround could be the used of coordinates as described from #1088.

As soon as the Appium bug is resolved, then we will try again.

Hope this helps,
Aurélien

**Comment by j0hnsa** [comment] 2017-04-04 14:38
Hi @abourdon ,
I believe that this can be closed as the present workaround works without any problem.
Thanks

**Comment by abourdon** [comment] 2017-04-04 14:40
Hi @j0hnsa,

I'm happy to know this workaround is working but it is not portable if you change device's screen size.

I prefer to let it opened until Appium's one will be fixed.

Regards,
Aurélien

**Comment by j0hnsa** [comment] 2018-04-30 16:46
Managed to workaround this issue with third party app (Go Keyboard) now the keypress works.

Regards

**Comment by nicodeur** [comment] 2018-05-28 15:40
Problem is always du to appium, i reopen a new issue : https://github.com/appium/java-client/issues/916.

Waiting resolution, you can use @j0hnsa workaround.

Regards

**Comment by tvincent59** [comment] 2019-03-05 17:01
Hello,

I think this problem is due to event KEYPESS_SEARCH is an event for hardkeyboard but the search button display on the screen send an event for softkeyboard (IME event).

A solution : http://appium.io/docs/en/writing-running-appium/android/android-ime/

**Closed** 2022-03-14 16:02 UTC
Labels: Nat : bug, Perim : ENGINEActionApps, Ori : LaRedoute
