### ISSUE TITLE
Tests list/TestCase list not respecting the system

### ISSUE THREAD

**Issue by TheSadlig** [cerberustesting/cerberus-source#1822] opened 2018-08-21 21:02 UTC
Hi,

In the list of the test cases and tests, the current system is not selected. This happens even if the user does not have the right to access the system.

How to reproduce:
1. Create a system A, with the application A1
2. Create a system B, with the application B1
3. Create a user ("UA1") with only the right to access the system A.
4. Create a test ("TA1") + testcase for the application A1
5. Create a test ("TB1") + testcase for the application B1
6. Connect as user UA1.
7. You will see both tests (TB1 and TA1), even if the application B1 is in the system B, which is not in the user's permission.

I have not found any issue matching this, perhaps my understanding of the systems is wrong.

If it is of any help:
Cerberus Version : 3.7.1-1359

Thanks
TheSadlig

**Comment by vertigo17** [comment] 2018-08-22 08:31
Yes this is a known issue. 
It is also part of the roadmap with no deadline yet. 
There is also already an issue open on the subject #1358 that has more informations and details so I close yours.
Duplicate of #1358.

**Closed by vertigo17** 2018-08-22 08:31 UTC
