### ISSUE TITLE
connection to active directory

### ISSUE THREAD

**Issue by kileurf** [cerberustesting/cerberus-source#1833] opened 2018-09-06 09:23 UTC
Hello,

could you provide use a support to the connection of Cerberus and an Active Directory ?

Regards

**Comment by vertigo17** [comment] 2018-09-07 19:39
Duplicate of https://github.com/cerberustesting/cerberus-source/issues/1180
Also part of Roadmap (but not yet priorized/planned).

**Closed by vertigo17** 2018-09-07 19:39 UTC
