### ISSUE TITLE
Regression with the CUSTOM swipe on iOS

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1547] opened 2017-11-10 11:18 UTC
Hi,

Custom swipe is not working on QA.

QA:
http://192.168.135.30/CerberusQA/TestCaseExecution.jsp?executionId=39918102
PROD:
http://192.168.134.17/Cerberus/TestCaseExecution.jsp?executionId=52582679

Regards
Cerberus Version : 2.1.0-SNAPSHOT-1249

**Comment by Nouxx** [comment] 2017-11-10 12:42
Anything similar to ticket #1524  ?

**Comment by Nouxx** [comment] 2017-11-10 12:44
Could you share with us any logs from Appium ? That could help solving the problem like we did for ticket #1524.

**Comment by j0hnsa** [comment] 2017-11-10 14:10
Hi,

Below are the logs of the swipe:

[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"x":158,"y":515,"duration":0}},{"action":"moveTo","options":{"x":158,"y":360}},{"action":"release","options":{}}],"eb3ff4ae-7181-4315-935b-800c6c3e4f90"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: longPress(options={"x":158,"y":515,"duration":0})-moveTo(options={"x":158,"y":360})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8312/session/93DEE7A5-C736-424D-BE30-33643F457A4F/wda/dragfromtoforduration] with body: {"fromX":158,"fromY":515,"toX":0,"toY":0,"duration":null}
[debug] [JSONWP Proxy] Got response with status 200: {"value":"-[NSNull doubleValue]: unrecognized selector sent to instance 0x1afe5eef8\n\n(\n\t0   CoreFoundation                      0x0000000189b8aff8 <redacted> + 148\n\t1   libobjc.A.dylib                     0x00000001885ec538 objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000189b91ef4 <redacted> + 0\n\t3   CoreFoundation                      0x0000000189b8ef54 <redacted> + 916\n\t4   CoreFoundation                      0x0000000189a8ad4c _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x0000000101cef490 +[FBElementCommands handleDragCoordinate:] + 600\n\t6   WebDriverAgentLib                   0x0000000101cd04c8 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208\n\t7   WebDriverAgentLib                   0x0000000101cc8344 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496\n\t8   RoutingHTTPServer                   0x0000000101d7a3cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t9   RoutingHTTPServer                   0...
[HTTP] <-- POST /wd/hub/session/eb3ff4ae-7181-4315-935b-800c6c3e4f90/touch/perform 500 83 ms - 5174
[HTTP] --> GET /wd/hub/session/eb3ff4ae-7181-4315-935b-800c6c3e4f90/screenshot {}
[debug] [MJSONWP] Calling AppiumDriver.getScreenshot() with args: ["eb3ff4ae-7181-4315-935b-800c6c3e4f90"]
[debug] [XCUITest] Executing command 'getScreenshot'
[debug] [JSONWP Proxy] Proxying [GET /screenshot] to [GET http://localhost:8312/session/93DEE7A5-C736-424D-BE30-33643F457A4F/screenshot] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : \"iVBORw0KGgoAAAANSUhEUgAAAoAAAARwCAYAAAB6j+UAAAAAAXNSR0IArs4c6QAA\\r\\nABxpRE9UAAAAAgAAAAAAAAI4AAAAKAAAAjgAAAI4AAgPKBCAPbkAAEAASURBVHgB\\r\\n1L33n5XVuf+tiT2KIkhvQxtgCgPD9N6ZyjAzlGHoVURAxK6o2HuLPUajiSYxiUk0\\r\\niUaNFQXpHdTYknO+p3yf52+4ns977X1tFzuYc57fzvnhfq11r3Wtcpe97s\\/+XGWd\\r\\nsu\\/TvxnH\\/s\\/+bgc+\\/xc7+Nd\\/DWmq7K+J+tS5ZJBD3g\\/qDkjOj4NfqO7zb8JBGXnK\\r\\nPB+f+3ixfJBLzice18cL8\\/xMcziuMT\\/9ux1U3g\\/OTyj7\\/G92UMeBzzQHpYf+Kvno\\r\\n3Nsd+vxfQx\\/MI\\/06OE\\/NX\\/PyNqTp8i7LdXGkxvN5auzDX\\/xLqpzrC3Jf6hqS94j0\\r\\nkM5TfSXPvZz2fj2H\\/\\/p\\/jIP5k\\/rcvIzxj3z57Txoy0EZh8\\/Fy13ez49+pf6T8yX1\\r\\nvjx\\/5It\\/S9XHfYa+mZfG9z59PG\\/r5S5DSt3RLxJzO\\/rNv+l6\\/tV27P\\/cdh36Ilxf\\r\\n3Aey3JNw\\/3T93l8sE571X7+2T7\\/+P3bsq\\/+wPUe+SvT1lcY4\\/oW9\\/9EO27b7mB3S\\r\\ndRz7+t\\/s+Df\\/rnG+sn2HP7NdB\\/9qOw4c13z+zY5+\\/Y299+EOe2vbLtu2c4e989Yf\\r\\n7If33G7LejpsWdcsW9\\/Xa5uXLbH1c2fbqo5G626ssN6ONuuaWWXFUzKtJj\\/fZpaX\\r\\nW3NVpY5qm1lZZS211dZcUWGl06da3qQJljtxopVPK7Cm8mprqa6xtvp666xvtFWL\\r\\n+mx+d7vVlBTZjMx...
[debug] [MJSONWP] Responding to client with driver.getScreenshot() result: "iVBORw0KGgoAAAANSUhEUgAAAoAAAARwCAYAAAB6j+UAAAAAAXNSR0IArs4c6QAA\r\nABxpRE9UAAAAAgAAAAAAAAI4AAAAKAAAAjgAAAI4AAgPKBCAPbkAAEAASURBVHgB\r\n1L33n5XVuf+tiT2KIkhvQxtgCgPD9N6ZyjAzlGHoVURAxK6o2HuLPUajiSYxiUk0\r\niUaNFQXpHdTYknO+p3yf52+4ns977X1tFzuYc57fzvnhfq11r3Wtcpe97s/+XGWd\r\nsu/TvxnH/s/+bgc+/xc7+Nd/DWmq7K+J+tS5ZJBD3g/qDkjOj4NfqO7zb8JBGXnK\r\nPB+f+3ixfJBLzice18cL8/xMcziuMT/9ux1U3g/OTyj7/G92UMeBzzQHpYf+Kvno\r\n3Nsd+vxfQx/MI/06OE/NX/PyNqTp8i7LdXGkxvN5auzDX/xLqpzrC3Jf6hqS94j0\r\nkM5TfSXPvZz2fj2H//p/jIP5k/rcvIzxj3z57Txoy0EZh8/Fy13ez49+pf6T8yX1\r\nvjx/5It/S9XHfYa+mZfG9z59PG/r5S5DSt3RLxJzO/rNv+l6/tV27P/cdh36Ilxf\r\n3Aey3JNw/3T93l8sE571X7+2T7/+P3bsq/+wPUe+SvT1lcY4/oW9/9EO27b7mB3S\r\ndRz7+t/s+Df/rnG+sn2HP7NdB/9qOw4c13z+zY5+/Y299+EOe2vbLtu2c4e989Yf\r\n7If33G7LejpsWdcsW9/Xa5uXLbH1c2fbqo5G626ssN6ONuuaWWXFUzKtJj/fZpaX\r\nW3NVpY5qm1lZZS211dZcUWGl06da3qQJljtxopVPK7Cm8mprqa6xtvp666xvtFWL\r\n+mx+d7vVlBTZjMxcmzo+24pzpllRTq5Ny5xkNYWl1lhRG9rWFZeHtDBrqlUWFqqv\r\nWmuurLWa4rIgVzo133LHTrQcHeQrp8+wxrKqIFc1o9RK86ZZ2bTpVpibaxUzijSP\r\n...
[HTTP] <-- GET /wd/hub/session/eb3ff4ae-7181-4315-935b-800c6c3e4f90/screenshot 200 179 ms - 783306
[HTTP] --> DELETE /wd/hub/session/eb3ff4ae-7181-4315-935b-800c6c3e4f90 {}
[debug] [MJSONWP] Calling AppiumDriver.deleteSession() with args: ["eb3ff4ae-7181-4315-935b-800c6c3e4f90"]
[debug] [BaseDriver] Event 'quitSessionRequested' logged at 1510321769822 (13:49:29 GMT+0000 (WET))
[Appium] Removing session eb3ff4ae-7181-4315-935b-800c6c3e4f90 from our master session list
[debug] [JSONWP Proxy] Proxying [DELETE /session/eb3ff4ae-7181-4315-935b-800c6c3e4f90] to [DELETE http://localhost:8312/session/93DEE7A5-C736-424D-BE30-33643F457A4F] with no body
[debug] [JSONWP Proxy] Got response with status 200: "{\n  \"value\" : {\n\n  },\n  \"sessionId\" : \"0F248338-2487-4902-B547-D13921B392BD\",\n  \"status\" : 0\n}"
[XCUITest] Shutting down sub-processes
[XCUITest] Shutting down iproxy process (pid 43752)
[debug] [XCUITest] iproxy exited with code 'null'
[XCUITest] Shutting down xcodebuild process (pid 43753)
[XCUITest] xcodebuild exited with code 'null' and signal 'SIGTERM'
[XCUITest] Setting '755' permissions to '/Users/itsqdtests/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs/Test/Attachments' folder
[XCUITest] Cleaning test logs in '/Users/itsqdtests/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs' folder
[debug] [iOS] Clearing log files
[debug] [iOS] Deleting '/Users/itsqdtests/Library/Developer/Xcode/DerivedData/WebDriverAgent-brdadhpuduowllgivnnvuygpwhzy/Logs'. Freeing 2.3M.
[debug] [iOS] Finished clearing log files
[debug] [iOSLog] Stopping iOS log capture
[debug] [BaseDriver] Event 'quitSessionFinished' logged at 1510321770640 (13:49:30 GMT+0000 (WET))
[debug] [MJSONWP] Received response: null
[debug] [MJSONWP] But deleting session, so not returning
[debug] [MJSONWP] Responding to client with driver.deleteSession() result: null
[HTTP] <-- DELETE /wd/hub/session/eb3ff4ae-7181-4315-935b-800c6c3e4f90 200 819 ms - 76
[Appium] Received SIGINT - shutting down

**Comment by j0hnsa** [comment] 2017-11-10 14:18
It seems that it doesn't work also with the normal swipe on this page:
http://192.168.135.30/CerberusQA/TestCaseExecution.jsp?executionId=39918112

**Comment by j0hnsa** [comment] 2017-11-10 14:46
What I find more strange is:

[HTTP] --> POST /wd/hub/session/460fbcb9-07f2-4adf-8a9c-e28f33313e2f/touch/perform {"actions":[{"action":"longPress","options":{"x":160,"y":378,"duration":1000}},{"action":"moveTo","options":{"x":160,"y":189}},{"action":"release","options":{}}]}
[debug] [MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"longPress","options":{"x":160,"y":378,"duration":1000}},{"action":"moveTo","options":{"x":160,"y":189}},{"action":"release","options":{}}],"460fbcb9-07f2-4adf-8a9c-e28f33313e2f"]
[debug] [XCUITest] Executing command 'performTouch'
[debug] [XCUITest] Received the following touch action: longPress(options={"x":160,"y":378,"duration":1000})-moveTo(options={"x":160,"y":189})-release(options={})
[debug] [XCUITest] Found matching gesture: drag
[debug] [JSONWP Proxy] Proxying [POST /wda/dragfromtoforduration] to [POST http://localhost:8312/session/92F0DBBF-4DDF-4044-AF7A-BD719CD043ED/wda/dragfromtoforduration] with body: {"fromX":160,**"fromY":378,"toX":0,"toY":0,"duration":null}**
[debug] [JSONWP Proxy] Got response with status 200: {"value":"-[NSNull doubleValue]: unrecognized selector sent to instance 0x1afe5eef8\n\n(\n\t0   CoreFoundation                      0x0000000189b8aff8 <redacted> + 148\n\t1   libobjc.A.dylib                     0x00000001885ec538 objc_exception_throw + 56\n\t2   CoreFoundation                      0x0000000189b91ef4 <redacted> + 0\n\t3   CoreFoundation                      0x0000000189b8ef54 <redacted> + 916\n\t4   CoreFoundation                      0x0000000189a8ad4c _CF_forwarding_prep_0 + 92\n\t5   WebDriverAgentLib                   0x0000000102203490 +[FBElementCommands handleDragCoordinate:] + 600\n\t6   WebDriverAgentLib                   0x00000001021e44c8 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208\n\t7   WebDriverAgentLib                   0x00000001021dc344 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496\n\t8   RoutingHTTPServer                   0x000000010228e3cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144\n\t9   RoutingHTTPServer                   0...
[HTTP] <-- POST /wd/hub/session/460fbcb9-07f2-4adf-8a9c-e28f33313e2f/touch/perform 500 26 ms - 5174

Seems that no matter what I put on the swipe (also setting the duration on that parameter this values seems to not change:

"fromY":378,"toX":0,"toY":0,"duration":null

**Comment by bcivel** [comment] 2017-11-23 16:11
Hello @j0hnsa 
Can you try it again on QA please?
Thanks

**Comment by j0hnsa** [comment] 2017-11-23 17:08
Hello @bcivel ,

Unfortunately still not working, I've attached appium logs.
[logs.txt](https://github.com/cerberustesting/cerberus-source/files/1499895/logs.txt)

Regards

**Comment by j0hnsa** [comment] 2017-12-05 11:49
Hello,

I've just tested and now the error is slightly different (Original error: Mobile swipe requires direction), can you check?
http://192.168.135.30/CerberusQA/TestCaseExecution.jsp?executionId=52792095

Regards

**Comment by vertigo17** [comment] 2017-12-05 11:59
Detail of the error message:

Failed to swipe 'CUSTOM' screen due to 'An unknown server-side error occurred while processing the command. Original error: Mobile swipe requires direction (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.6.0', revision: '6fbf3ec767', time: '2017-09-27T15:28:36.4Z'
System info: host: 'app009.siege.red', ip: '192.168.135.30', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-327.13.1.el7.x86_64', java.versio

![2017-12-05 12_57_57-execution detail](https://user-images.githubusercontent.com/5342048/33605977-1c3c1536-d9bc-11e7-81c0-4475f7570b01.png)

**Comment by j0hnsa** [comment] 2017-12-21 10:22
Hi all,

Managed to test with appium 1.6.4 but the error persists.
Attached the server logs.
[logs.txt](https://github.com/cerberustesting/cerberus-source/files/1578835/logs.txt)

Regards

**Comment by Nouxx** [comment] 2017-12-21 13:20
This should be the interessting part (the actual swipe) : 
```
[debug] [MJSONWP] Responding to client with driver.getWindowSize() result: {"width":320,"height":568}
[HTTP] <-- GET /wd/hub/session/2bfdcf42-9fe8-41c2-8d55-f9e96824fb3f/window/current/size 200 316 ms - 98 
[HTTP] --> POST /wd/hub/session/2bfdcf42-9fe8-41c2-8d55-f9e96824fb3f/execute {"script":"mobile: swipe","args":[{"duration":0,"endY":343,"endX":153,"startY":546,"startX":153}]}
[debug] [MJSONWP] Calling AppiumDriver.execute() with args: ["mobile: swipe",[{"duration":0,"endY":343,"endX":153,"startY":546,"startX":153}],"2bfdcf42-9fe8-41c2-8d55-f9e96824fb3f"]
[debug] [XCUITest] Executing command 'execute'
[debug] [BaseDriver] Waiting up to 0 ms for condition
[debug] [JSONWP Proxy] Proxying [POST /element] to [POST http://localhost:8003/session/809A46AC-E5C0-4AEE-A0BE-1E10E52D2F67/element] with body: {"using":"class name","value":"XCUIElementTypeApplication"}

```

**Comment by bcivel** [comment] 2018-01-08 22:19
Hello @j0hnsa 
Don't know if you noticed (I didn't myself before ;-) ) but we switched from the deprecated appium action `swipe`, to the appium action commands `touch action, moveTo, release`.

Doing that, we moved from absolute coordinate to the relative ones (target relative to source). And on appium, before the last version, IOS switched to relative coordinate when Android were still absolute. That explain the issue you've met.

So, for now, we have 2 ways to handle that case. 
 - Either we keep like that and we change our tests to put relatives coordinate (to be near the appium current implementation)
 - Or we keep absolute in Cerberus as it was previously in appium, and we forward the relative to appium.

@j0hnsa, @vertigo17 what do you suggest?
Thanks

**Comment by vertigo17** [comment] 2018-01-09 08:01
Considering that swipe action is used only for Appium backend, I would suggest to stay as cloase as we can from Appium. That will simplify support and understanding of the action.
That means that I perfer we change the test.
We need to add in the changelog the warning in order to identify all impacted actions and what to change. I would propose we put in the changelog the SQL that will identify the list of actions to correct.

**Comment by bcivel** [comment] 2018-01-22 21:45
Hi @j0hnsa 
Should be fixed with my last commit. 
I executed the test from @vertigo17 on Browserstack and I can confirm that swipe is now working fine (direction UP,DOWN,LEFT,RIGHT, and CUSTOM).
Please, notice that for custom swipe, coordinate are relative and no more absolute.
I upgrade the changelog accordingly

**Closed by bcivel** 2018-01-22 21:45 UTC
Labels: Nat : bug, Perim : ENGINEActionApps, Prio : 0 high++

**Comment by j0hnsa** [comment] 2018-01-23 10:33
I can confirm that is working as expected.

Thanks!
