### ISSUE TITLE
[IDEA] - Possibility to attach several ticket id to a testcase in execution

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1926] opened 2019-01-14 14:35 UTC
Hello,

What do you think about adding the possiblity to add several tickets # in a single test case execution?
It is currently possible to assign only one

Thanks!

**Comment by vertigo17** [comment] 2020-01-19 17:59
duplicate of #1946

**Closed by vertigo17** 2020-01-19 17:59 UTC
Labels: Nat : enhancement, Perim : GUIExecution, Prio : 2 normal
