### ISSUE TITLE
Data Library client side wrong value display

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1748] opened 2018-06-04 14:04 UTC
Steps to reproduce: 
- Edit a Library and set a Service

![image](https://user-images.githubusercontent.com/30227758/40921374-93cb144e-680f-11e8-839e-a9c6e1d3c7b2.png)

- Save the change
- Refresh the page
- Edit the same Data Library

![image](https://user-images.githubusercontent.com/30227758/40921617-4239d718-6810-11e8-9e6e-22e83395a3d5.png)

A quick search in DB show that the value is saved:
![image](https://user-images.githubusercontent.com/30227758/40921700-7fb9aa0a-6810-11e8-965e-5762beaa98c1.png)

Clicking in the 'Save' button will save the Data Library with an empty value (even in DB)

I think that the client side code is setting the value to null when the modal is re-opened.

**Comment by ryltar** [comment] 2018-06-04 14:22
not able to reproduce this issue :/

**Comment by ryltar** [comment] 2018-06-04 19:44
yes, i think the same ! the input take a value which isn't currently loaded. I will check this next week. We could have the same problem on all modal.

**Comment by Nouxx** [comment] 2018-06-05 07:30
Maybe the jQuery .ready() function can solve this issue?

I wanted to give it a try with this, to make sure the modal is feeded when fully loaded

```
    $('#editTestDataLibModal').ready(function() {
    	feedDataLibModal(dataLibEntry, "editTestDataLibModal", "EDIT");
    });
```
_source/src/main/webapp/js/transversalobject/DataLib.js - line 219-222_

It's not breaking anything in my dev environment but I don't have enough items in it to actually try. Should I commit it in order to try in our QA env?

**Comment by vertigo17** [comment] 2018-06-05 19:48
in order to simulate a slow responsetime on a specific API you can use inside ServletUtil class inside package: org.cerberus.util.servlet

                    case "/ReadAppService":
                        timeToWait = 3000;
                        break;
inside switch:
switch (request.getServletPath()) {

Having done that issue is reproduced.

In order to fix it, I prefered to init the Datalib modal 
    initModalDataLib();
when loading the main Datalib page.

We can keep the issue open in order to implement a select2 on that combo as the list could be pretty big on some system and should avoid to load the full table on the modal.

**Comment by vertigo17** [comment] 2018-06-06 05:10
partialy fixed in https://github.com/cerberustesting/cerberus-source/commit/32d313644416f58df227fa845a7fbf1352142457

**Comment by Nouxx** [comment] 2018-06-08 15:54
It's working on our QA

**Closed** 2018-07-20 22:08 UTC
Labels: Nat : bug, Perim : GUIData, Prio : 3 minor
