### ISSUE TITLE
Be able to see the detail of a property (or another object) without changing screen (refactoring). 

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-source#1473] opened 2017-09-08 15:06 UTC
Hello Benoît

I created the ticket :-) 
For example, when you edit the use case, you can see the properties. And when you need to see the detail of one values of the properties, you must open a new screen to 

the ticket is managed by RYLTAR and BCIVEL. 

Thanks 
best regards
Peggy

**Comment by vertigo17** [comment] 2017-09-21 20:09
Looks like duplicate of both #1366 and #1363 that are more precise.
If confirmed, @MowglieRed, can you close it ?

**Comment by vertigo17** [comment] 2018-01-10 17:42
Detail of property on modal is accessible when action is CalculateProperty but the idea would be to display it also for any other Fields as long as we use a property (with %property.PROPNAME%)

**Comment by vertigo17** [comment] 2018-03-12 15:48
Modal is available anytime the property is used.

**Closed by vertigo17** 2018-03-12 15:48 UTC
Labels: Nat : enhancement, Perim : GUITest, Prio : 1 high+
