### ISSUE TITLE
No Tooltips on Firefox on the report by tag on the header of the table

### ISSUE THREAD

**Issue by MichaelWil** [cerberustesting/cerberus-source#1425] opened 2017-08-02 08:20 UTC
Hi,

Using Firefox 54.0.1, displaying a report (for exemple http://cerberus.siege.red/Cerberus/ReportingExecutionByTag.jsp?Tag=WEB_THESEUS_ALL_PREPROD_2017073112).
I don't see any tooltip when hovering the header of the table, while it's displayed on the other place.
![2017-08-02_101745](https://user-images.githubusercontent.com/11719918/28864201-0f4f4378-776c-11e7-957a-015975dfdb1d.jpg)

Can you please take a look and fix ?

Thanks !

**Comment by bcivel** [comment] 2017-08-21 20:33
Hello @vertigo17 
Can you confirm you able to reproduce it? From my side, cannot reproduce on any browser.
And during our last exchange, @MichaelWil confirmed that it doesn't happen anymore on his side.
Thanks

**Comment by vertigo17** [comment] 2017-08-23 07:46
yes I also have the issue. Tested with firefox 45.3.0:
![2017-08-23 09_39_03-execution reporting by tag](https://user-images.githubusercontent.com/5342048/29604169-ef4805fc-87e6-11e7-814b-a3e8a1d5a2ac.png)
Display no tooltip.

But the strange thing is that it is working fine on chrome (Version 60.0.3112.101) but also on Firefox 55.0.2:

![2017-08-23 09_40_03-execution reporting by tag](https://user-images.githubusercontent.com/5342048/29604212-1a1a6e5a-87e7-11e7-8917-6969e6f9cd36.png)

I propose to close the issue as working with latest version of browser.

**Closed** 2017-08-23 19:45 UTC
