### ISSUE TITLE
Test Case Execution: Dependency Tab

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1978] opened 2019-05-09 09:54 UTC
Hello,

Can we add a Dependency Tab in the Execution Detail page to provide for each dependency :
- the Test & TestCase 
- the execution status
- a link to this execution

Thanks

**Comment by vertigo17** [comment] 2019-08-08 14:17
Duplicate of #1970

**Closed by vertigo17** 2019-08-08 14:17 UTC
