### ISSUE TITLE
New control VerifyStatusCode

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#2094] opened 2020-02-14 08:32 UTC
Hello,

I think it would be great to add a new control "VerifyStatusCode" with a single field for the status code expected. It would be more user friendly than the actual way to test status code : 
![image](https://user-images.githubusercontent.com/18569182/74514278-8357e980-4f0c-11ea-9cc5-455a2b6aa361.png)

**Comment by vertigo17** [comment] 2020-07-19 19:39
I suggest that as a duplicate of #2088 that will allow to control all the JSON from the service call.
It will allow test on Status but also http headers.

**Closed by vertigo17** 2020-07-19 19:39 UTC
