### ISSUE TITLE
Issue with jsonpath expression in Cerberus

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1275] opened 2017-04-11 16:49 UTC
Hello,
I have an issue with jsonpath expression, for example the following expression works on the website tester but not on Cerberus.
$.testCaseStepExecutionList[0]..testCaseStepActionControlExecutionList..returnCode
https://jsonpath.curiousconcept.com/
I want to get the result of the first step.
The execution is : 
http://demo.cerberus-testing.org:28081/Cerberus/ExecutionDetail2.jsp?executionId=405
Could you have a look please ?

The response is : 
_{"testCaseStepExecutionList":[{"useStepTestCase":"","conditionOper":"always","returnMessage":"","description":"Execute control (expected OK)","fullEnd":0,"returnCode":"OK","loop":"onceIfConditionTrue","end":1491928743249,"id":406,"useStep":"N","fileList":[],"conditionVal2":"","test":"ENGINE : Control","conditionVal1":"","useStepTest":"","start":1491928743224,"conditionVal2Init":"","index":1,"sort":1,"testcase":"0001B","timeElapsed":0,"testCaseStepActionExecutionList":[{"forceExeStatus":"","conditionOper":"always","value2":"","value1":"","returnMessage":"","description":"Execute control VerifyStringEqual","value1init":"","returnCode":"OK","testCaseStepActionControlExecutionList":[{"conditionOper":"always","controlValueInit":"String1","returnMessage":"'String1' is equal to 'String1'.","description":"Verify the two strings are equal","fatal":"Y","returnCode":"OK","controlProperty":"String1","end":1491928743243,"id":406,"fileList":[],"controlPropertyInit":"String1","conditionVal2":"","test":"ENGINE : Control","conditionVal1":"","conditionVal2Init":"","controlValue":"String1","start":1491928743243,"index":1,"endlong":0,"control":1,"sort":1,"testcase":"0001B","sequence":1,"controlType":"verifyStringEqual","step":1,"conditionVal1Init":"","startlong":0}],"action":"doNothing","end":1491928743232,"id":406,"fileList":[],"conditionVal2":"","test":"ENGINE : Control","conditionVal1":"","conditionVal2Init":"","start":1491928743232,"index":1,"endlong":0,"sort":1,"testcase":"0001B","sequence":1,"step":1,"value2init":"","conditionVal1Init":"","startlong":1491928743228}],"fullStart":1491928743224,"step":1,"useStepTestCaseStep":-1,"conditionVal1Init":""},{"useStepTestCase":"","conditionOper":"always","returnMessage":"'String2' is not equal to 'String1'.","description":"Execute control (expected KO)","fullEnd":0,"returnCode":"KO","loop":"onceIfConditionTrue","end":1491928743281,"id":406,"useStep":"N","fileList":[],"conditionVal2":"","test":"ENGINE : Control","conditionVal1":"","useStepTest":"","start":1491928743259,"conditionVal2Init":"","index":1,"sort":2,"testcase":"0001B","timeElapsed":0,"testCaseStepActionExecutionList":[{"forceExeStatus":"","conditionOper":"always","value2":"","value1":"","returnMessage":"'String2' is not equal to 'String1'.","description":"Execute control VerifyStringEqual","value1init":"","returnCode":"KO","testCaseStepActionControlExecutionList":[{"conditionOper":"always","controlValueInit":"String2","returnMessage":"'String2' is not equal to 'String1'.","description":"Verify the two strings are equal","fatal":"Y","returnCode":"KO","controlProperty":"String1","end":1491928743276,"id":406,"fileList":[],"controlPropertyInit":"String1","conditionVal2":"","test":"ENGINE : Control","conditionVal1":"","conditionVal2Init":"","controlValue":"String2","start":1491928743276,"index":1,"endlong":0,"control":1,"sort":1,"testcase":"0001B","sequence":1,"controlType":"verifyStringEqual","step":2,"conditionVal1Init":"","startlong":0}],"action":"doNothing","end":1491928743268,"id":406,"fileList":[],"conditionVal2":"","test":"ENGINE : Control","conditionVal1":"","conditionVal2Init":"","start":1491928743268,"index":1,"endlong":0,"sort":1,"testcase":"0001B","sequence":1,"step":2,"value2init":"","conditionVal1Init":"","startlong":1491928743264}],"fullStart":1491928743259,"step":2,"useStepTestCaseStep":-1,"conditionVal1Init":""}],"country":"FR","controlStatus":"KO","crbVersion":"Cerberus-1.1.12-SNAPSHOT","conditionOper":"","platform":"","browserFullVersion":"","screenSize":"","browser":"","testCaseObj":{"conditionOper":"","testCaseStepList":[{"conditionVal2":"","useStepTestCase":"","test":"ENGINE : Control","conditionOper":"always","conditionVal1":"","inLibrary":"N","useStepTest":"","description":"Execute control (expected OK)","sort":1,"testcase":"0001B","initialStep":0,"testCaseStepActionList":[{"forceExeStatus":"","conditionVal2":"","test":"ENGINE : Control","conditionOper":"always","conditionVal1":"","value2":"","value1":"","screenshotFilename":"","description":"Execute control VerifyStringEqual","sort":1,"testcase":"0001B","sequence":1,"action":"doNothing","step":1,"testCaseStepActionControlList":[{"conditionVal2":"","test":"ENGINE : Control","conditionOper":"always","conditionVal1":"","value2":"String1","value1":"String1","screenshotFilename":"","description":"Verify the two strings are equal","control":"verifyStringEqual","sort":1,"testcase":"0001B","fatal":"Y","sequence":1,"step":1,"conditionVal2AAAA":""}]}],"loop":"onceIfConditionTrue","step":1,"useStepStep":-1,"useStep":"N"},{"conditionVal2":"","useStepTestCase":"","test":"ENGINE : Control","conditionOper":"always","conditionVal1":"","inLibrary":"N","useStepTest":"","description":"Execute control (expected KO)","sort":2,"testcase":"0001B","initialStep":0,"testCaseStepActionList":[{"forceExeStatus":"","conditionVal2":"","test":"ENGINE : Control","conditionOper":"always","conditionVal1":"","value2":"","value1":"","screenshotFilename":"","description":"Execute control VerifyStringEqual","sort":1,"testcase":"0001B","sequence":1,"action":"doNothing","step":2,"testCaseStepActionControlList":[{"conditionVal2":"","test":"ENGINE : Control","conditionOper":"always","conditionVal1":"","value2":"String2","value1":"String1","screenshotFilename":"","description":"Verify the two strings are equal","control":"verifyStringEqual","sort":1,"testcase":"0001B","fatal":"Y","sequence":1,"step":2,"conditionVal2AAAA":""}]}],"loop":"onceIfConditionTrue","step":2,"useStepStep":-1,"useStep":"N"}],"howTo":"","description":"As a Cerberus user, I can execute a testcase script with a verifyStringEqual","fromRev":"","implementer":"","activePROD":"N","fromBuild":"","dateCreated":"2017-03-27 17:38:01.0","refOrigine":"","function":"","activeQA":"Y","group":"AUTOMATED","test":"ENGINE : Control","ticket":"","usrModif":"admin","toBuild":"","conditionValue2":"","origine":"","priority":0,"conditionValue1":"","testcase":"0001B","usrCreated":"admin","behaviourOrValueExpected":"","tcActive":"Y","targetRev":"","activeUAT":"Y","usrAgent":"","application":"CerberusEngine","bugId":"","comment":"","targetBuild":"","dateModif":"2017-03-28 17:51:09.0","toRev":"","status":"TO BE VALIDATED"},"end":1491928743289,"id":406,"tag":"","fileList":[],"capabilities":["org.cerberus.crud.entity.RobotCapability@1d55bda"],"conditionVal2":"","test":"ENGINE : Control","conditionVal1":"","controlMessage":"The test case finished, but failed on validations.","ip":"benoitcivel1","testCaseExecutionDataList":[],"start":1491928743185,"conditionVal2Init":"","finished":"N","userAgent":"","version":"","testcase":"0001B","url":"","revision":"","verbose":0,"environment":"QA","application":"CerberusEngine","build":"","port":"XXXXXXXX","environmentData":"QA","conditionVal1Init":"","status":"TO BE VALIDATED"}_

Cerberus Version : 1.1.11-SNAPSHOT-1108

**Comment by abourdon** [comment] 2017-04-19 09:40
Sorry but I'm unable to reproduce from the current SNAPSHOT version.

Computing the JSONPath value from `$.testCaseStepExecutionList[0]..testCaseStepActionControlExecutionList..returnCode`, gives me `[OK]` as expected from the JSONPath online evaluator (https://jsonpath.curiousconcept.com/):

<img width="1432" alt="screen shot 2017-04-19 at 11 34 55" src="https://cloud.githubusercontent.com/assets/1511715/25173451/6cad7dfc-24f4-11e7-8ee2-c3f47146c28d.png">

And so, the control fails because expecting `OK` and not `[OK]` (maybe you should edit your JSONPath expression or control expectation value to match with the right string):

<img width="1049" alt="screen shot 2017-04-19 at 11 34 44" src="https://cloud.githubusercontent.com/assets/1511715/25173470/7b4702ac-24f4-11e7-9317-e5e24e500712.png">

Could you please update your Cerberus version to the current SNAPSHOT version and try again?

Thanks,
Aurélien

**Comment by abourdon** [comment] 2017-04-26 13:25
QA has just been deployed with latest SNAPSHOT version and result is the same from my side in local: http://demo.cerberus-testing.org:28080/CerberusQA/ExecutionDetail2.jsp?executionId=195

So we can close this issue.

Please update the production version to this one and test again.

Regards,
Aurélien

**Closed by abourdon** 2017-04-26 13:25 UTC
Labels: Perim : ENGINEProperty, Prio : major, Status : question
