### ISSUE TITLE
Add campaign tags variables

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1945] opened 2019-02-27 10:33 UTC
Hello,
We'd really like an evolution of the tag parameterized in the campaign definition.
It will be perfect to be able to use parameters %country% and %environment%.

- If the tag refers to a campaign executed on a single country (or environment), %country% will return this single country. Ex: "FR"
- If the tag refers to a campaign executed on multiple countries (or environment), %country% will return a join of these countries. Ex: "FR-BE-IT"

In our usage of Cerberus here, in Leroy, this upgrade will enormously improve our effectiveness.

**Comment by vertigo17** [comment] 2019-03-01 13:11
In fact this is quite hard to determine when tag is created on which scope the executions will be done.
(Tag is created when the 1st execution enter in the queue).
System even allow to submit 2 campaigns at the same time on the same tag ;-).
What I can suggest is that we add an environment and country columns at tag level (not a variable in tag name) that would be feed at the end of the tag execution with that information.
It would be done at the same time we calculate the various execution statistics.

Would that fit the need ?

**Comment by SeniorCanard** [comment] 2019-03-05 13:54
It may feet the need. I just have 2 questions: 
- Will the "environment and country columns at tag level" be on the runTestCase screen or in the campaign definition screen?
- With your proposition, the tag at first execution and the tag at the end of the campaign will not be the same? Does this include upcoming executions (a test with same tag but on another country and/or environment will change the tag) ?

**Comment by vertigo17** [comment] 2019-03-08 17:28
1/ no it will be at tag level and could appear on ReportByTag screen in 
![image](https://user-images.githubusercontent.com/5342048/54044377-13ef5b00-41cf-11e9-9241-a12d4dcf4541.png)
or in campaign statistics modal under campaign screen:
![image](https://user-images.githubusercontent.com/5342048/54044440-3e411880-41cf-11e9-8851-e3b523a2e9e3.png)
It will contain the list of environment / country where there were at least 1 execution under that tag.

2/ When you submit a campaign, Cerberus automaticly created a tag at the beginning of the execution. The same tag is updated at the end of all executions (once no more execution are in the queue) with global stats. If you trigger a new execution on the same tag before the queue is empty, that execution will be taken into account. If you trigger it after the queue has been empty and tag execution is finished, it will not be updated.

**Comment by vertigo17** [comment] 2019-04-26 19:36
Duplicate of https://github.com/cerberustesting/cerberus-source/issues/1815

**Closed by vertigo17** 2019-04-26 19:36 UTC
Labels: Nat : enhancement, Perim : Queueing system, Prio : 2 normal
