### ISSUE TITLE
[TestCase] Looping on step until condition reached

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1037] opened 2016-11-30 13:50 UTC
Hi,

I have a problem with an Android app where i dont know in advance the behavior.

The test case can vary from 50 pages to 60 pages, basically the same page, some page contains mandatory field.
But i cant predict in which page the mandatory field will be present, it vary every time 

What i need : 

```
if an element is present 
-> do action
Next page 
```

So, is there a way to achieve this ?

Thank you

Victorien

**Comment by vitoo** [comment] 2016-11-30 16:26
As a workarround i've used 'PE' to ignore fail if element not found

But the 'Loop' thing case is still a problem for my case, making a huge test case, lagging browser etc 
As you can see in this screenshot : 

http://puu.sh/szyCL/e1047e64b2.png

**Comment by vertigo17** [comment] 2016-12-20 21:22
Closing the issue as duplicate of #1007

**Closed by vertigo17** 2016-12-20 21:22 UTC
Labels: Perim : ENGINETransversal
