### ISSUE TITLE
Create/Edit Data Library - '+' character is replaced by space ' '

### ISSUE THREAD

**Issue by maclog** [cerberustesting/cerberus-source#1610] opened 2018-02-09 15:55 UTC
Hi,

In the Data Libraries, in SQL query using the '+' (plus) character is not properly saved. The '+' is replaced by a space ' ' character. This happens whether creating a new datalib or editing a existing one.

![image](https://user-images.githubusercontent.com/9317996/36036229-427707f0-0db1-11e8-8cf5-16d5a690c50a.png)

**Comment by vertigo17** [comment] 2018-02-10 13:09
I was not able to reproduce with latest version.
I created a Test Data Library with + inside SQL Script field.
I also created an empty one modifying with + in SQL Script.
In both cases, The + appear when editing the testdatalib but also checking the database directly.

Tested with both:
Chrome Version 64.0.3282.140 (Official Build) (64-bit)
Firefox 57.0.4 (64-bit)

**Comment by ryltar** [comment] 2018-02-12 10:32
This bug was resolved with this commit fbcb2828cf2723cf25d15498eb500adc2ef02014 (07/02/2018)

**Closed** 2018-02-12 10:32 UTC
Labels: Nat : bug, Perim : GUIData, Prio : 1 high+, Status : waiting feedback
