### ISSUE TITLE
Filter by Labels on Report By Tag page

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2073] opened 2020-01-15 10:48 UTC
Hello, 

I believe it can be useful to filter by labels (stickers) on the List tab of the report by tag page ?

Some of our campaigns are 'splitted' by features (checkout,...) on the same campaign, so filtering can be useful for the analysis !

Thanks

**Comment by vertigo17** [comment] 2020-02-09 21:36
this issue is duplicate of #2084

**Closed by vertigo17** 2020-02-09 21:36 UTC
Labels: Nat : enhancement, Perim : GUIExecution, Prio : 2 normal
