### ISSUE TITLE
Hide the SYSTEMS that are not selected in a user profile

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1359] opened 2017-07-04 08:36 UTC
Hi,

in the list of SYSTEMS (on the top right of the window)
<img width="185" alt="capture d ecran 2017-07-04 a 10 33 08" src="https://user-images.githubusercontent.com/14962879/27821920-352f6f0c-60a4-11e7-9536-e7f6c0eabea0.png">

Why a user, for who we chosen only one allowed sytem, it is able to change for another one?

Does the others systems should be not accessible according to the users's permissions?

Thanks.

**Comment by vertigo17** [comment] 2018-07-24 19:21
Duplicate of #1358

**Closed by vertigo17** 2018-07-24 19:21 UTC
Labels: Nat : enhancement, Perim : GUITransversal, Prio : 3 minor
