### ISSUE TITLE
Data Library are not fetching number in Service Call

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2154] opened 2020-07-22 15:30 UTC
Hello,

When using a Service Data Library and getting this result : 
```
{
  "unknown": [],
  "success": [{
    "entity_code": 507989,
    "entity_type": "ITEM",
    "sale_at_loss": null,
    "price": {
      "value_with_taxes": 32.95,
      "value_without_taxes": 27.55,
      "start_date": "2013-02-14T00:00:00+01:00",
      "end_date": "9999-12-31T23:59:59.999+01:00",
      "price_type": "STANDARD",
      "margin_stock": null,
      "margin_expected": null,
      "currency": "EUR",
      "is_store_price": true
    }
  }]
}
```

The following jsonpath in the Parsing Answer : `$.success[0].entity_code` which works in a [tester](https://jsonpath.herokuapp.com/) returns this error in Cerberus 
![image](https://user-images.githubusercontent.com/30227758/88195725-a23b7400-cc40-11ea-9c43-ce887886392d.png)

The **ClassCastException** exception seems to be the issue since I tried with a string attribute `$.success[0].entity_type` and it works fine:
![image](https://user-images.githubusercontent.com/30227758/88195932-e3338880-cc40-11ea-944c-abe06a71c884.png)

**Comment by vertigo17** [comment] 2020-07-29 09:28
I could not reproduce.
Can you create a test in prod.cerberus-testing.org in order to reproduce.
You can use service : http://localhost:8080/Cerberus/DummyRESTCall
It return the same structure as yours.
I used $.myArray[0].integer and $.myArray[0].val2 for fetching 2 sub data and it return a correct result.
![image](https://user-images.githubusercontent.com/5342048/88782941-79f6cc80-d18e-11ea-9107-05773cec17f6.png)

![image](https://user-images.githubusercontent.com/5342048/88782977-84b16180-d18e-11ea-87d2-23a8b4d393ed.png)


![image](https://user-images.githubusercontent.com/5342048/88783020-94c94100-d18e-11ea-9559-b4b3d13a6118.png)

**Comment by vertigo17** [comment] 2020-07-29 15:42
I implemented a testcase that will be inside tomorow NRT campaign.
I let you check it as currently it is working fine.
It calculate 2 Datalib that call JSON services.
1 has only 1 row mapping and the other one has 10 row lines (using both string and integer as sub data)

**Comment by vertigo17** [comment] 2020-07-30 05:11
Here is the implemented test:
https://prod.cerberus-testing.org/TestCaseScript.jsp?test=ENGINE%20:%20Property&testcase=0012A

Also message was improved avoiding mentioning SOAP when it was not ;-)

**Comment by Nouxx** [comment] 2020-08-06 08:17
Hi, 

that seemed weird to me too.

I'll share with you the exact Cerberus logs as soon as I can 

Thanks !

**Closed** 2020-09-10 13:35 UTC
Labels: Nat : bug, Perim: ENGINEActionSRV, Prio : 2 normal
