### ISSUE TITLE
[Activation Conditions][Edit TestCase Header]

### ISSUE THREAD

**Issue by hananema** [cerberustesting/cerberus-source#2285] opened 2021-08-19 09:57 UTC
Hello,

I noticed an issue concerning activation conditions: when a test has one and we modify the test case header, the condition disappears without losing the condition operator.
Example:
My test has this activation condition:
![image](https://user-images.githubusercontent.com/41586025/130048069-acf2823b-96b6-4c02-9a41-632ec713beb5.png)
And when I refresh the page and edit test case header, this is what happens:
![image](https://user-images.githubusercontent.com/41586025/130048267-97f91299-83f6-4a84-909f-f6ee43a829b1.png)

And when I save the modification, the testCase will not be executed:
![image](https://user-images.githubusercontent.com/41586025/130048570-9b8f4d37-a3dd-4dc6-873e-2a125c218a5f.png)

Could you please check.

Thank you
Hanane

**Comment by vertigo17** [comment] 2021-08-19 11:07
Which version do you use ?
I can't reproduce in qa.cerberus-testing.com

This is what I did:
Open a testcase from testcaselist page to testcasescript page.
From testcase script page, I open the header and set condition with value1, 2 and 3 defined.
Saved the modal.
Reopen the modal and the data was still there.
Saved the script
Reopen the modal and the data was still there.

I also checked on database and I never lost the data.
Maybe I did not perform the correct actions.

Can you detail more the actions to reproduce ?

**Comment by hananema** [comment] 2021-08-19 11:33
Here is how I reproduce:
1- open a testcase script
2- go to edit test case header
3- set condition (for me it was IfStringDifferent and value 1 and 2 defined)
4- save header modification
5- refresh the page 
6- go to edit test case header

Current result: codition operator is still there but value 1 and 2 are emptied 
Expected: acivation condition should still be configured 

PS: This hapens even if you save the script after saving the header, you don't even need to refresh the page in this case, if you just go to edit header after saving the script you get the same issue.

Cerberus version: Cerberus4.12-SNAPSHOT-1583 Build 20210303-092801
Browser: Chrome

**Comment by MorganLmd** [comment] 2021-08-19 11:50
Hello @vertigo17, with @hananema we have tried to reproduce this bug on QA testing and QA redoute with no results. Both are with version 4.13 and prod Redoute is with 4.12, maybe it has been fixed with the latest version ?

**Comment by vertigo17** [comment] 2021-08-19 11:54
This is what I though.
Still can't reproduce either from QA ;-(.
You are right, it was probably already fixed...
1 more reason to move to latest version ;-)
I close the issue.

**Closed by vertigo17** 2021-08-19 11:54 UTC
Labels: Nat : bug, Perim : GUITest, Prio : 2 normal
