### ISSUE TITLE
QE is still present in report after retries finished with OK

### ISSUE THREAD

**Issue by plockynt** [cerberustesting/cerberus-source#2248] opened 2021-04-26 16:30 UTC
Hello,

We are using Cerberus 4.11.2 and we encountered a situation that causes some issues.

When we are looking at an execution report, it seems that the campaign ran successfully, but when looking at tag detail, we see a QE status, even though the campaign report has OK status. Is this a bug, or a display that we didn't understood ?

Below is a screenshot illustrating the situation I am describing :
![Cerberus_QE_as_OK](https://user-images.githubusercontent.com/60100565/116117593-b3784c00-a6bc-11eb-8b2e-ea5fa0b65082.png)

**Comment by vertigo17** [comment] 2021-04-26 18:49
This is not a bug ;-).
The part on the below on the screenshot (1 OK and 1 QE) display the initial results of the campaign execution (it ended at 9:52 with 1 OK and 1 QE).
The part on the top display the latest result (including the last execution you may have submitted in order to improve the result). In that case, I guess you relaunched the QE execution at 9:53:45 and it ended in OK status.

NB : The initial result is also the result of the campaign execution without any intervention and allow to keep track of campaign quality over time. That information can also be seen in 'Campaign report over time'
I close the issue but we can reopen it in case my hypothesis is wrong ;-).

**Closed by vertigo17** 2021-04-26 18:49 UTC
