### ISSUE TITLE
[LR] - What about the purge treatment of the cerberus database 

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-source#2324] opened 2021-11-24 07:58 UTC
Hello Everybody,

I have a question for you about the purge treatment on the cerberus database. 

Currently, we developped a purge treatment of the cerberus database. To develop it, we need to have a good knowledge of the physical model in order to respect the foreign key. 

Each time we deploy a release cerberus, we need to review all the SQL applied to detect the create and the drop table. Sometimes the updates just to verify the rename of existing columns. 

My question is : 
What about to propose a purge treatment template developped and maintained by the communauty  ? And when you deploy a release, you deploy a new version of the script including the create/drop tables ?  

Like that the users of cerberus decides or not to use the script and they can set up the purge delay ? 

Thanks for your return. 
Peggy (LaRedoute)

**Comment by vertigo17** [comment] 2022-02-02 22:43
duplicate of #565 that was closed due to complexity of potential rules.
If we create that script, more likely that everyone will copy it to tune it and loose the benefit.
In SaaS mode, we maintain those script 'manualy' also and tune them according to our need ;-).

**Closed by vertigo17** 2022-02-02 22:43 UTC
Labels: Ori : LaRedoute
