### ISSUE TITLE
open ReportingExecutionByTag url load

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1270] opened 2017-04-11 08:51 UTC
When opening the ReportingExecutionByTag page using url (examples: from browser history, from skype link...) the page does not open and stays like this:
![image](https://cloud.githubusercontent.com/assets/1914659/24900588/40fc7f18-1e9c-11e7-92dd-174e39901341.png)

Clicking 'load' the pages load immediately.

**Comment by vertigo17** [comment] 2017-04-11 11:37
I was not able to reproduce. Did you try in QA ?
Can you give a URL example that reproduce the issue ?
Do I need to close the browser before opening the URL ?

**Comment by vertigo17** [comment] 2017-07-09 18:53
@ruirpr is this issue still present ?
If not, can you close it. If yet, please detail how to reproduce the issue. Is that intermitent ?

**Closed** 2017-08-01 21:20 UTC
Labels: Nat : bug, Perim : GUIExecution, Prio : minor, Status : question
