### ISSUE TITLE
Labels: possibility to have n-level hierarchy

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1802] opened 2018-07-20 13:58 UTC
Hello,

What do you think of being able to have more than 2 levels of hierarchy ?

Currently, you can only select a 'parent' label in the **Parent LabelID** menu:

![image](https://user-images.githubusercontent.com/30227758/43006254-8225f53e-8c35-11e8-8275-6118a72324a9.png)

**Comment by vertigo17** [comment] 2018-07-25 10:00
Already included on #1572.
Just to be clear, I don't thing we should allow a label to belong to more than 1 label. 
For me what needs to be done is to allow a label to have a parent that also have another parent that also have another parent ,etc...
We can already do that byfeeding the Parent Label ID but that data is not yet used  on the screen above 2 levels.
Can you confirm that type of hierarchy is fine and the only purpose of the issue is to have n levels of hierarchy in the same model. As a consequence that issue could be duplicate of #1572

**Comment by Nouxx** [comment] 2018-07-25 10:02
@ntennich

**Closed** 2018-07-26 01:08 UTC
Labels: Nat : enhancement, Perim : GUILabel, Prio : 2 normal
