### ISSUE TITLE
Appium behavior change ? Broke all our tests ...

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1103] opened 2017-01-09 09:43 UTC
Hi,

I've updated cerberus to c72c6441 

Appium android test case are not executed the same way, it looks like now it doesnt wait elements loading before doing an action

So it stop testcase while loading : 

![image](https://cloud.githubusercontent.com/assets/995694/21762294/3a0c94c2-d658-11e6-8c59-770193f87aa8.png)

I've set cerberus_appium_wait_element to 6000 

Any idea ?

**Comment by bcivel** [comment] 2017-01-09 09:57
Hi @vitoo 
Does it stop before waiting 6 seconds? 
How long does he wait?
Thanks
Benoit

**Comment by vitoo** [comment] 2017-01-09 10:10
Here it wait only 500 ms : 

![image](https://cloud.githubusercontent.com/assets/995694/21763037/1f0f8090-d65c-11e6-9961-c9081aaa627d.png)

Still loading : 
![image](https://cloud.githubusercontent.com/assets/995694/21763044/25a70658-d65c-11e6-8ae7-6e32451defa0.png)

Before it waited 3320 ms : 
![image](https://cloud.githubusercontent.com/assets/995694/21763062/39fefc14-d65c-11e6-947b-e6ebe0664ba3.png)

**Comment by bcivel** [comment] 2017-01-09 10:15
And what is your value for this parameter cerberus_selenium_wait_element?
Thanks

**Comment by vitoo** [comment] 2017-01-09 10:16
3500 ms

**Comment by vitoo** [comment] 2017-01-09 10:37
I place some wait to workarround this 👍

**Comment by vitoo** [comment] 2017-01-09 13:20
Any idea ?

If a fix can avoid me to edit 30 test cases

**Comment by abourdon** [comment] 2017-03-15 16:48
Hi @vitoo,

So this issue could be closed?

Regards,
Aurélien

**Comment by abourdon** [comment] 2017-03-29 13:30
As this is not an issue I think we can close it

**Comment by vitoo** [comment] 2017-03-29 13:35
Hi,

I had to edit 30 test case and add 10 wait per testcase to handle this

**Comment by vertigo17** [comment] 2017-03-29 17:45
Does not seems to be acceptable.
Let's reopen until we find a good solution (even if it takes time).

**Comment by abourdon** [comment] 2017-03-29 18:25
Ok I was not aware about regression

**Comment by bcivel** [comment] 2017-03-29 19:56
linked to https://github.com/appium/java-client/issues/574

**Comment by vertigo17** [comment] 2018-01-30 21:51
@vitoo , can you confirm if with latest version of Cerberus (3.0 integrate the latest version of Appium) it fix the issue ?

**Comment by vitoo** [comment] 2018-01-30 22:02
No i can't (old mission)

But i remember this problem was due to the queue change in cerberus, by setting the pool size it fixed this 

So i think we can closed this issue :smile:

**Closed** 2018-05-02 15:09 UTC
Labels: Perim : ENGINEActionApps
